language: elixir

elixir:
  - 1.7.0

addons:
  postgresql: "9.4"

services:
  - postgresql

otp_release:
  - 19.0

env:
  - MIX_ENV=test

script:
  - mix format --check-formatted
  - mix test
  - mix coveralls.travis
